style: Remove unused structs
`cargo clippy` reports:

```
error: struct `StoredObjectField` is never constructed
  --> graphql_client_codegen/src/schema.rs:14:8
   |
14 | struct StoredObjectField {
   |        ^^^^^^^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`

error: struct `ObjectFieldId` is never constructed
  --> graphql_client_codegen/src/schema.rs:51:19
   |
51 | pub(crate) struct ObjectFieldId(usize);
   |                   ^^^^^^^^^^^^^

error: struct `InputFieldId` is never constructed
  --> graphql_client_codegen/src/schema.rs:72:8
   |
72 | struct InputFieldId(usize);
   |        ^^^^^^^^^^^^
```